# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerEngineStub(object):
    """SchedulerEngine — runs as a standalone gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSchedule = channel.unary_stream(
                '/scheduler.SchedulerEngine/RunSchedule',
                request_serializer=scheduler__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ScheduleUpdate.FromString,
                _registered_method=True)
        self.ValidateData = channel.unary_unary(
                '/scheduler.SchedulerEngine/ValidateData',
                request_serializer=scheduler__pb2.ValidateRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/scheduler.SchedulerEngine/Ping',
                request_serializer=scheduler__pb2.PingRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PingResponse.FromString,
                _registered_method=True)


class SchedulerEngineServicer(object):
    """SchedulerEngine — runs as a standalone gRPC service
    """

    def RunSchedule(self, request, context):
        """Run schedule optimization. Streams progress updates, then final result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateData(self, request, context):
        """Validate input data (health check) without running the solver.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Service liveness check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSchedule': grpc.unary_stream_rpc_method_handler(
                    servicer.RunSchedule,
                    request_deserializer=scheduler__pb2.ScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.ScheduleUpdate.SerializeToString,
            ),
            'ValidateData': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateData,
                    request_deserializer=scheduler__pb2.ValidateRequest.FromString,
                    response_serializer=scheduler__pb2.ValidateResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=scheduler__pb2.PingRequest.FromString,
                    response_serializer=scheduler__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.SchedulerEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.SchedulerEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerEngine(object):
    """SchedulerEngine — runs as a standalone gRPC service
    """

    @staticmethod
    def RunSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scheduler.SchedulerEngine/RunSchedule',
            scheduler__pb2.ScheduleRequest.SerializeToString,
            scheduler__pb2.ScheduleUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerEngine/ValidateData',
            scheduler__pb2.ValidateRequest.SerializeToString,
            scheduler__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerEngine/Ping',
            scheduler__pb2.PingRequest.SerializeToString,
            scheduler__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
